import {Component, HostListener, OnDestroy, OnInit} from '@angular/core';
import {GridApi, GridOptions, GridReadyEvent} from 'ag-grid-community';

@Component({
    selector: 'app-list',
    templateUrl: './list.component.html',
    styles: []
})
export class ListComponent implements OnInit, OnDestroy {
    gridApi: any;
    gridColumnApi: any;
    public gridOptions: GridOptions = {
        defaultColDef: {
            flex: 1,
            minWidth: 100,
            enableValue: true,
            enableRowGroup: true,
            enablePivot: true,
            sortable: true,
            filter: true,
        },
        pagination: true,
        paginationPageSize: 10,
        rowSelection: 'single',
        domLayout: 'autoHeight',
        rowGroupPanelShow: 'always',
        pivotPanelShow: 'always',
        sideBar: true,
    };
    private resizeListenerFunc = () => { this.gridApi.sizeColumnsToFit(); };

    public columnDefs = [
        {
            headerName: 'Activity Summary',
            children: [
                { headerName: '', field: 'selected', checkboxSelection: true, resizeable: false, minWidth: 50, maxWidth: 50 },
                { headerName: 'Violation State', field: 'violation_state', resizeable: false, minWidth: 180},
                { headerName: '1 Day', field: 'summary_1_day', resizeable: false, minWidth: 90, maxWidth: 90},
                { headerName: '7 Days', field: 'summary_7_day', resizeable: false, minWidth: 90, maxWidth: 90},
                { headerName: '30 Days', field: 'summary_30_day', resizeable: false, minWidth: 100, maxWidth: 100},
            ]
        },
        {
            headerName: 'Violation Summary - 411',
            children: [
                { headerName: 'State', field: 'state', maxWidth: 150, minWidth: 150},
                { headerName: 'Listing #', field: 'listing_num'},
                { headerName: 'Status', field: 'status', maxWidth: 150, minWidth: 150},
                { headerName: 'Violation #', field: 'violation_num', maxWidth: 150, minWidth: 150},
                { headerName: 'Agent', field: 'agent'},
                { headerName: 'Office', field: 'office'},
                { headerName: 'Violation Name', field: 'violation_name'},
                { headerName: 'Date', field: 'date', maxWidth: 130, minWidth: 130},
                { headerName: 'Modified Date', field: 'modified_date', maxWidth: 130, minWidth: 130},
            ]
        },

    ];
    public rowData = [
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        }
    ];

    onGridReady(params: GridReadyEvent): void {
        this.gridApi = params.api;
        this.gridColumnApi = params.columnApi;
        this.gridApi.sizeColumnsToFit();
        window.addEventListener('resize', this.resizeListenerFunc);
    }

    ngOnDestroy(): void {
       window.removeEventListener('resize', this.resizeListenerFunc);
    }

    constructor() {

    }

    ngOnInit(): void {
    }

    gotoDetails() {
        window.location.href = '/details';
    }

}
