import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-list',
    templateUrl: './list.component.html',
    styles: []
})
export class ListComponent implements OnInit {

    autoGroupColumnDef = {
        resizable: true,
        cellRendererParams: {
            checkbox: true
        }
    };
    sideBar = {
        toolPanels: [
            {
                id: 'columns',
                labelDefault: 'Columns',
                labelKey: 'columns',
                iconKey: 'columns',
                toolPanel: 'agColumnsToolPanel',
            },
            {
                id: 'filters',
                labelDefault: 'Filters',
                labelKey: 'filters',
                iconKey: 'filter',
                toolPanel: 'agFiltersToolPanel',
            }
        ],
        defaultToolPanel: null
    };

    public columnDefs = [
        {
            headerName: 'Activity Summary',
            children: [
                { headerName: '', field: 'selected', checkboxSelection: true, width: 50, suppressSizeToFit: false },
                { headerName: 'Violation State', field: 'violation_state', sortable: true, width: 180, suppressSizeToFit: false},
                { headerName: '1 Day', field: 'summary_1_day', sortable: true, width: 80, suppressSizeToFit: false},
                { headerName: '7 Days', field: 'summary_7_day', sortable: true, width: 80, suppressSizeToFit: false},
                { headerName: '30 Days', field: 'summary_30_day', sortable: true, width: 90, suppressSizeToFit: false},
            ]
        },
        {
            headerName: 'Violation Summary - 411',
            children: [
                { headerName: 'State', field: 'state', sortable: true, width: 100, suppressSizeToFit: false},
                { headerName: 'Listing #', field: 'listing_num', sortable: true, width: 100, suppressSizeToFit: false},
                { headerName: 'Status', field: 'status', sortable: true, width: 100, suppressSizeToFit: false},
                { headerName: 'Violation #', field: 'violation_num', sortable: true, width: 120, suppressSizeToFit: false},
                { headerName: 'Agent', field: 'agent', sortable: true, width: 200, suppressSizeToFit: false},
                { headerName: 'Office', field: 'office', sortable: true, width: 200, suppressSizeToFit: false},
                { headerName: 'Violation Name', field: 'violation_name', sortable: true, width: 200, suppressSizeToFit: false},
                { headerName: 'Date', field: 'date', sortable: true, width: 100, suppressSizeToFit: false},
                { headerName: 'Modified Date', field: 'modified_date', sortable: true, width: 100, suppressSizeToFit: false},
            ]
        },
    ];

    public rowData = [
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        },
        {
            violation_state: 'Detected',
            summary_1_day: 'xxx',
            summary_7_day: 'xxx',
            summary_30_day: 'xxx',
            state: 'New',
            listing_num: 3280408,
            status: 'Active',
            violation_num: '2860048',
            agent: 'Lando Calrission',
            office: 'Acme MLS',
            violation_name: 'Unbranded VR Tour URL',
            date: 'xx/xx/xxxx',
            modified_date: 'xx/xx/xxxx',
        }
    ];

    constructor() {
    }

    ngOnInit(): void {
    }

}
